version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip stepFunction.json
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - update-state-machine \
        --zip-file fileb://deployment_package.zip
        --role-arn arn:aws:iam::992200940678:role/service-role/StepFunctions-HelloWorld-role-00108854 \
        --state-machine-arn arn:aws:states:us-east-1:992200940678:stateMachine:HelloWorld


