AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  
  ValidationStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      DefinitionUri: statemachine/validator.asl.json
      DefinitionSubstitutions:
        ValidateOwnerFunctionArn: !GetAtt ValidateOwnerFunction.Arn
        ValidatePropertyFunctionArn: !GetAtt ValidatePropertyFunction.Arn
        ValidationSuccesfullFunctionArn: !GetAtt ValidationSuccesfullFunction.Arn
        ValidationNotSuccesfullFunctionArn: !GetAtt ValidationNotSuccesfullFunction.Arn
